epcData <- read.table("household_power_consumption.txt",header = TRUE,sep = ";",colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'),na.strings = '?')
epcDataSub <- subset(epcData,Date == "1/2/2007" | Date == "2/2/2007")
png(filename = "plot1.png")
with(epcDataSub, hist(as.numeric(Global_active_power), col = "red", ,main = "Global Active Power",xlab = "Global Active Power (kilowatts)"))
dev.off()